version: 1
meta:
  title: "Decompose Boxes - マルチルート例"
  author: "copilot"
  slide_size: { preset: "16x9" }

slides:
  - id: "decompose_multi"
    background: "#FFFFFF"
    components:
      - tool: "decompose_boxes"
        id: "decompose_test"
        pos: { x: 5, y: 30, w: 40, h: 40 }
        data:
          root:
            name: "Application"
            children:
              - name: "Frontend"
                children:
                  - name: "Components"
                  - name: "Pages"
              - name: "Backend"
                children:
                  - name: "API"
                  - name: "Database"
